name: Minions
version: 1.0
main: me.ayush_03.minions.Main
api-version: 1.15
description: A custom Minions plugin made by Ayush_03 Development Services.

commands:
     minion:
         usage: /minion <player> <type>
         description: Gives the speicified player a Minion spawner.